- name: Ansible playbook to setup void linux
  hosts: all

  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/system/_main.yml
    - import_tasks: tasks/terminal/_main.yml
    - import_tasks: tasks/development/_main.yml
    - import_tasks: tasks/desktop/_main.yml
    - import_tasks: tasks/gaming/_main.yml

