- name: Start and enable syncthing
  tags: ["once"]
  systemd:
    name: syncthing@{{ user }}
    enabled: true
    state: started 
  become: true

- name: Set hostname for linux
  tags: ["once"]
  shell: >
    hostnamectl set-hostname {{ hostname }}
  become: true

- name: Change sudo settings
  lineinfile:
    path: /etc/sudoers
    regexp: ^Defaults    env_reset
    line: Defaults    env_reset,timestamp_timeout=60,!tty_tickets
  become: yes
