- name: Install terminal void packages
  xbps:
    name:
      - neovim # Vim-fork focused on extensibility and agility
      - task # Command-line TODO list manager
      - timewarrior # Timewarrior tracks and reports time
      - python3-tasklib # Library for interacting with taskwarrior databases (Python3)
      - vifm # Ncurses-based file manager with vi-like keybindings
      - zsh # Z SHell
      - tmux # Terminal Multiplexer
      - nmap # Utility for network discovery and security auditing
      - w3m  # Text-based Web browser and pager (with Debian patches)
      - lf # Terminal file manager
      - khal # Command-line calendar build around CalDAV
      - khard # Command-line addressbook built around CardDAV
      - vdirsyncer # Synchronize calendars and addressbooks
      - neofetch # Simple system information script
    state: present
  become: true

- name: Install terminal python packages
  ansible.builtin.pip:
    name: 
      - pynvim 

- name: Install terminal xbps-src packages 
  tags: ["src"]
  include_tasks: ../include/xbps-src.yml
  loop:
    - package: rbw # Unofficial command line client for bitwarden
      repository: hostdir/binpkgs

- include_tasks: nb.yml # Command line and local web note‑taking, bookmarking, archiving, and knowledge base application
- include_tasks: taskwarrior-tui.yml # Terminal User Interface (TUI) for Taskwarrior
