- name: Install gaming fedora packages
  dnf:
    name:
      - lutris # Video game preservation platform
      - gamemode # Optimize system performance for games on demand
      - wine # A compatibility layer for windows applications
    state: present
  become: true

- name: Install gaming flatpaks
  flatpak:
    name:
      - com.valvesoftware.Steam
    state: present
  become: true
