- name: Add vscode repo 
  tags: ["once"]
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey:  https://packages.microsoft.com/keys/microsoft.asc
  become: true