- name: Install development dnf packages
  xbps:
    name:
      - python3
      - python3-pip # A tool for installing and managing Python3 packages
      - ripgrep
      - fd
      - lazygit
    state: present
  become: true

- name: Install development python packages
  ansible.builtin.pip:
    name: 
      - ansible-lint # Command-line tool for linting playbooks, roles and collections 

- name: Install development flatpaks
  flatpak:
    name:
      - com.vscodium.codium # Free/Libre Open Source Software Binaries of VS Code
    state: present
  become: true
