- name: Make advcpmv directory
  file:
    path: /home/{{ user }}/tmp/advcpmv
    state: directory

- name: Download advcpmv file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jarun/advcpmv/master/install.sh
    dest: /home/{{ user }}/tmp/advcpmv/install.sh

- name: Compile advcp and advmv
  command:
    cmd: sh /home/{{ user }}/tmp/advcpmv/install.sh
    creates: /home/{{ user }}/tmp/advcpmv/advcp
    chdir: /home/{{ user }}/tmp/advcpmv 

- name: Move advcp
  copy:
    src: /home/{{ user }}/tmp/advcpmv/advcp
    dest: /usr/local/bin/cpg
    mode: preserve
  become: true

- name: Move advmv
  copy:
    src: /home/{{ user }}/tmp/advcpmv/advmv
    dest: /usr/local/bin/mvg
    mode: preserve
  become: true
