[".themes/dracula"]
    type = "archive"
    url = "https://github.com/dracula/gtk/archive/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
    type = "git-repo"
    url = "https://github.com/wbthomason/packer.nvim.git"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".task"]
    type = "git-repo"
    url = "git@github.com:starr-dusT/task.git"
    refreshPeriod = "168h"

### OLD ###
#[".config/xmonad/xmonad"]
#    type = "git-repo"
#    url = "https://github.com/xmonad/xmonad"
#    refreshPeriod = "168h"
#
#[".config/xmonad/xmonad-contrib"]
#    type = "git-repo"
#    url = "https://github.com/xmonad/xmonad-contrib"
#    refreshPeriod = "168h"
#
#[".config/xmonad/xmobar"]
#    type = "git-repo"
#    url = "https://codeberg.org/xmobar/xmobar"
#    refreshPeriod = "168h"
