[".themes/dracula"]
    type = "archive"
    url = "https://github.com/dracula/gtk/archive/master.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
    type = "git-repo"
    url = "https://github.com/wbthomason/packer.nvim.git"
    refreshPeriod = "168h"

[".task"]
    type = "git-repo"
    url = "git@github.com:starr-dusT/task.git"
    refreshPeriod = "168h"

["documents/zet"]
    type = "git-repo"
    url = "git@github.com:starr-dusT/zet.git"
    refreshPeriod = "168h"
