themes:
    gruvbox:
        bg0: '#282828'
        bg1: '#3c3836'
        bg2: '#504945'
        fg: '#d5c4a1'
        black: '#282828'
        red: '#fb4934'
        green: '#b8bb26'
        yellow: '#fabd2f'
        blue0: '#83a598'
        blue1: '#458588'
        purple0: '#d3869b'
        purple1: '#8f3f71'
        cyan: '#8ec07c'
        white: '#d5c4a1'
