#!/usr/bin/env bash
# https://github.com/starr-dusT/dotfiles

# nixos
alias nu="cd ~/.local/share/chezmoi/provision && \
          sudo nixos-rebuild switch --impure --flake .#$(hostname) && \
          cd -"
alias nb="cd ~/.local/share/chezmoi/provision && \
          sudo nix run .#nixosConfigurations.wsl.config.system.build.tarballBuilder && \
          cd -"

# sesh
function b() {
  {
    exec </dev/tty
    exec <&1
    local session
    session=$(sesh list -i | fzf --ansi --height 40% --reverse --border-label ' sesh ' --border --prompt '⚡  ')
    [[ -z "$session" ]] && return
    sesh connect $session
  }
}

# chezmoi
alias cc="cd ~/.local/share/chezmoi"
alias ca="chezmoi apply"
alias ce='chezmoi edit'

# trashcli
alias tp='trash-put'
alias te='trash-empty'
alias tl='trash-list'
alias tre='trash-restore'
alias trm='trash-rm'

# git
alias gs="git status"
alias gc="git commit"
alias ga="git add ."
alias gd="git diff"
alias gl="git log"

# rsync
alias rsync.net="ssh fm2120@fm2120.rsync.net"
