#!/usr/bin/env bash
# https://github.com/starr-dusT/dotfiles

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then 
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"; 
fi

if ! [[ "$PATH" =~ "$HOME/.nimble/bin:" ]]; then 
    PATH="$HOME/.nimble/bin:$PATH"; 
fi

if ! [[ "$PATH" =~ "$HOME/.cargo/bin:" ]]; then  
    PATH="$HOME/.cargo/bin:$PATH" ; 
fi
export PATH
