#!/bin/sh
case $1 in
    "home")
        # Primary monitor on left
        xrandr --output DP-4 --primary \
            --mode 2560x1440 --rate 144 \
            --pos 0x0 --rotate normal \
            --output HDMI-0 \
            --mode 2560x1440 --rate 144 \
            --pos 2560x0 --rotate normal
        ;;
    "apt")
        # Primary monitor on right
        xrandr --output HDMI-0 \
            --mode 2560x1440 --rate 144 \
            --pos 0x0 --rotate normal \
            --output DP-4 --primary \
            --mode 2560x1440 --rate 144 \
            --pos 2560x0 --rotate normal
        ;;
esac
