- name: Install system fedora packages
  dnf:
    name:
      - git # Fast Version Control System
      - git-lfs # Git extension for versioning large files
      - syncthing # Continuous File Synchronization
      - flatpak # Application deployment framework for desktop apps
      - wireguard-tools # Fast, modern, secure vpn tunnel
      - pipewire-codec-aptx # PipeWire Bluetooth aptX codec plugin
      - ansible # Simple deployment, configuration management and execution framework
      - build-essential
      - qemu-system 
      - libvirt-daemon-system
      - trash-cli # Command line interface to the freedesktop.org trashcan
      - android-tools # Android platform tools(adb, fastboot)
      - snapper
      - python3-dnf-plugin-snapper
      - cargo
      - borgbackup
      - fzf
      - chezmoi
    state: present
  become: true
