- name: Get {{ item.repo }} release information
  uri:
    url: https://api.github.com/repos/{{ item.user }}/{{ item.repo }}/releases/latest
    return_content: true
  register: repo_latest 

- name: Install un-archived {{ item.repo }} - {{ repo_latest.json.tag_name }}
  loop: "{{ repo_latest.json.assets }}"
  when: "asset.name is regex(item.regex)"
  get_url:
    url: "{{ asset.browser_download_url }}"
    dest: /home/{{ user }}/.local/bin/{{ item.repo }}
    mode: 0775
  when: item.name is not defined
  get_url:
    url: "{{ asset.browser_download_url }}"
    dest: /home/{{ user }}/.local/bin/{{ item.name }}
    mode: 0775
  when: item.name is defined
  loop_control:
    loop_var: asset
