- name: Start and enable syncthing
  tags: ["once"]
  systemd:
    name: syncthing@{{ user }}
    enabled: true
    state: started 
  become: true

- name: Set hostname for linux
  tags: ["once"]
  shell: >
    hostnamectl set-hostname {{ hostname }}
  become: true

- name: Change sudo settings
  lineinfile:
    path: /etc/sudoers
    regexp: ^Defaults    env_reset
    line: Defaults    env_reset,timestamp_timeout=60,!tty_tickets
  become: yes

- name: Enable modeset for nvidia
  tags: ["once"]
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!nvidia_drm.modeset=1).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 nvidia_drm.modeset=1"'
    backup: true
    backrefs: true
  become: yes

- name: Update grub
  tags: ["once"]
  shell: >
    grub-mkconfig -o /boot/grub/grub.cfg
  become: true
