- name: Start and enable syncthing
  tags: ["once"]
  systemd:
    name: syncthing@{{ user }}
    enabled: true
    state: started 
  become: true

- name: Set hostname for linux
  tags: ["once"]
  shell: >
    hostnamectl set-hostname {{ hostname }}
  become: true

- name: Change sudo settings
  lineinfile:
    path: /etc/sudoers
    regexp: ^Defaults    env_reset
    line: Defaults    env_reset,timestamp_timeout=60,!tty_tickets
  become: yes

- name: Add user to libvirt group
  tags: ["once"]
  shell: |
    usermod -a -G libvirt {{ user }} 
  become: true

- name: Start and enable dbus-broker 
  tags: ["once"]
  systemd:
    name: dbus-broker 
    enabled: true
    state: started 
  become: true
    
- name: Start and enable dbus-broker globally
  tags: ["once"]
  systemd:
    name: dbus-broker 
    scope: global
    enabled: true
    state: started 
  become: true
