- name: Install system packages
  pacman:
    name:
      - git # Fast Version Control System
      - git-lfs # Git extension for versioning large files
      - syncthing # Continuous File Synchronization
      - flatpak # Application deployment framework for desktop apps
      - wireguard-tools # Fast, modern, secure vpn tunnel
      #- pipewire-codec-aptx # PipeWire Bluetooth aptX codec plugin
      - ansible # Simple deployment, configuration management and execution framework
      - base-devel 
      - qemu
      - virt-manager
      - dnsmasq
      - iptables
      - trash-cli # Command line interface to the freedesktop.org trashcan
      - cargo
      - borgbackup
      - fzf
      - unzip
      - chezmoi
      - dbus-broker
      - vulkan-tools
      - fuse2
    state: present
  become: true

- name: Add flatpak remote 
  ansible.builtin.shell: |
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: true
