- name: Install system arch packages
  pacman:
    name:
      - git # Fast Version Control System
      - git-lfs # Git extension for versioning large files
      - syncthing # Continuous File Synchronization
      - flatpak # Application deployment framework for desktop apps
      - wireguard-tools # Fast, modern, secure vpn tunnel
      - libfreeaptx # PipeWire Bluetooth aptX codec plugin
      - ansible # Simple deployment, configuration management and execution framework
      - trash-cli # Command line interface to the freedesktop.org trashcan
      - android-tools # Android platform tools(adb, fastboot)
      - snapper
      - cargo
      - chezmoi
      - linux
      - linux-headers
      - linux-zen
      - linux-zen-headers
      - base-devel
      - python-setuptools
      - pipewire
    state: present
  become: true

- name: Add the flathub flatpak repository remote
  tags: ["once"]
  shell: |
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: true
