#!/usr/bin/env bash

tmux rename-window vortex-1
tmux send-keys -t edit-vortex:vortex-1 "ssh tstarr@vortex-1" Enter
tmux send-keys -t edit-vortex:vortex-1 "clear" Enter
tmux new-window -n vortex-2
tmux send-keys -t edit-vortex:vortex-2 "ssh tstarr@vortex-2" Enter
tmux send-keys -t edit-vortex:vortex-2 "clear" Enter
tmux new-window -n vortex-3
tmux send-keys -t edit-vortex:vortex-3 "ssh tstarr@vortex-3" Enter
tmux send-keys -t edit-vortex:vortex-3 "clear" Enter
tmux select-window -t 1
