- name: Set custom gnome binding {{ index }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ index }}/binding"
    value: "{{ item.bind }}"
    state: present

- name: Set custom gnome command {{ index }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ index }}/command" 
    value: "{{ item.command }}"
    state: present

- name: Set custom gnome name {{ index }}
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom{{ index }}/name"
    value: "{{ index }}"
    state: present