name: dotfiles
on: push

jobs:
  void:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Pull docker image
        run: docker-compose pull

      - name: Run installer on Void
        run: docker-compose up --build --exit-code-from dotfiles
